In [1]:
import tensorflow as tf

In [13]:
x = tf.constant(4, shape=(1, 2), dtype=tf.float32)
x = tf.constant([[1, 3, 4], [2, 3, 4]])
x = tf.ones((3, 3))
x = tf.zeros((2, 2))
x = tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [17]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
x = tf.random.uniform((1, 3), minval=0, maxval=1)
x = tf.range(start=1, limit=10, delta=2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [28]:
a = tf.constant([1, 2, 3])
b = tf.constant([1, 2, 3])
c = tf.add(a, b)
c = a + b #other similar -, /, x

c = tf.tensordot(a, b, axes=1)
c = tf.reduce_sum(a+b, axis=0)

c = a ** 10

a = tf.random.normal((2, 3))
b = tf.random.normal((3, 4))
c = tf.matmul(a, b)
c = a @ b
c

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-1.8622005 , -5.88496   , -1.1009535 , -2.060773  ],
       [-0.5296087 , -0.8453227 , -0.07225274, -0.5379475 ]],
      dtype=float32)>

In [37]:
x = tf.constant([1 ,2, 3, 4, 5, 6, 7, 8])
# x[:]
# x[1:]
# x[1:3]
# x[0:]
# x[:5]
# x[0::2]

indices = tf.constant([2, 7])
get_indices = tf.gather(x, indices)
get_indices

x = tf.constant([[1, 3],
                 [2, 4],
                 [3, 4]])
x[0, : ]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3])>

In [40]:
x = tf.range(9)
x
x = tf.reshape(x, (3, 3))
x
x = tf.transpose(x, perm=[1, ])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>