# **Classification**

In [1]:
import numpy as np
x = np.array([[[0, 0], [0, 1], [1, 0], [1, 1]]])
y = np.array([0, 1, 1, 1])

In [2]:
x

array([[[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]])

In [3]:
y

array([0, 1, 1, 1])

In [4]:
w = np.array([1, 1])
w

array([1, 1])

In [5]:
b = -0.5

In [8]:
def activation(z):
    if np.isscalar(z):  # Check if z is a scalar
        return 1 if z >= 0 else 0
    else:  # If it's an array, use np.where for element-wise operation
        return np.where(z >= 0, 1, 0)


In [9]:
pred = []
for a in x:
    y_hat = np.dot(a, w) + b
    pred.append(activation(y_hat))

In [10]:
pred


[array([0, 1, 1, 1])]

In [11]:
import math


In [13]:
epochs = 100
alpha = 0.2

In [14]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()
print(w0, w1, w2)

0.14647099744833836 0.9076891479490262 0.906767192484312


In [15]:
del_w0 = 1
del_w1 = 1
del_w2 = 1

In [16]:
train_data_temp = [[1, 1, 1], [1, 1, 0], [1, 0, 1], [1, 0, 0], [0, 1, 1], [0, 1, 0],
                   [0, 0, 1], [0, 0, 0]]
train_data = np.asarray(train_data_temp)
op = np.array([1, 1, 1, 1, 1, 1, 1, 0])

In [17]:
train_data

array([[1, 1, 1],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 0],
       [0, 1, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [18]:
bias = 0
for i in range(epochs):
    j = 0
    for x in train_data:
        y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias

        if y_hat >= 0:
            act = 1
        else:
            act = 0

        err = op[j] - act

        del_w0 = alpha * x[0] * err
        del_w1 = alpha * x[1] * err
        del_w2 = alpha * x[2] * err

        w0 = w0 + del_w0
        w1 = w1 + del_w1
        w2 = w2 + del_w2

        j += 1
        print('epoch=', i+1, 'error=', err)
        print(del_w0, del_w1, del_w2)

print('w0=', w0, 'w1=', w1, 'w2=', w2)

epoch= 1 error= 0
0.0 0.0 0.0
epoch= 1 error= 0
0.0 0.0 0.0
epoch= 1 error= 0
0.0 0.0 0.0
epoch= 1 error= 0
0.0 0.0 0.0
epoch= 1 error= 0
0.0 0.0 0.0
epoch= 1 error= 0
0.0 0.0 0.0
epoch= 1 error= 0
0.0 0.0 0.0
epoch= 1 error= -1
-0.0 -0.0 -0.0
epoch= 2 error= 0
0.0 0.0 0.0
epoch= 2 error= 0
0.0 0.0 0.0
epoch= 2 error= 0
0.0 0.0 0.0
epoch= 2 error= 0
0.0 0.0 0.0
epoch= 2 error= 0
0.0 0.0 0.0
epoch= 2 error= 0
0.0 0.0 0.0
epoch= 2 error= 0
0.0 0.0 0.0
epoch= 2 error= -1
-0.0 -0.0 -0.0
epoch= 3 error= 0
0.0 0.0 0.0
epoch= 3 error= 0
0.0 0.0 0.0
epoch= 3 error= 0
0.0 0.0 0.0
epoch= 3 error= 0
0.0 0.0 0.0
epoch= 3 error= 0
0.0 0.0 0.0
epoch= 3 error= 0
0.0 0.0 0.0
epoch= 3 error= 0
0.0 0.0 0.0
epoch= 3 error= -1
-0.0 -0.0 -0.0
epoch= 4 error= 0
0.0 0.0 0.0
epoch= 4 error= 0
0.0 0.0 0.0
epoch= 4 error= 0
0.0 0.0 0.0
epoch= 4 error= 0
0.0 0.0 0.0
epoch= 4 error= 0
0.0 0.0 0.0
epoch= 4 error= 0
0.0 0.0 0.0
epoch= 4 error= 0
0.0 0.0 0.0
epoch= 4 error= -1
-0.0 -0.0 -0.0
epoch= 5 error= 0
0.0 0.